#ifndef MELODIES_H
#define MELODIES_H

#include "sound_fun_rtttl.h"

// Melodía 1: Twinkle Twinkle Little Star
static const ToneFrequency twinkleMelody[] = {
  LOW_C, LOW_C, LOW_G, LOW_G, LOW_A, LOW_A, LOW_G,  // C4, C4, G4, G4, A4, A4, G4
  LOW_F, LOW_F, LOW_E, LOW_E, LOW_D, LOW_D, LOW_C   // F4, F4, E4, E4, D4, D4, C4
};

static const ToneDuration twinkleDurations[] = {
  MEDIUM_DURATION, MEDIUM_DURATION, MEDIUM_DURATION, MEDIUM_DURATION, MEDIUM_DURATION, MEDIUM_DURATION, LONG_DURATION,
  MEDIUM_DURATION, MEDIUM_DURATION, MEDIUM_DURATION, MEDIUM_DURATION, MEDIUM_DURATION, MEDIUM_DURATION, LONG_DURATION
};

static const size_t TWINKLE_MELODY_LENGTH = sizeof(twinkleMelody) / sizeof(twinkleMelody[0]);

// Melodía 2: El vuelo del moscardón (Nikolai Rimsky-Korsakov)
static const ToneFrequency flightOfTheBumblebeeMelody[] = {
  // Primera frase: A, G#, A, F#, G#, E, F#, D, E, C#, D, B, C#, A, B, G#
  MEDIUM_A, MEDIUM_G_SHARP, MEDIUM_A, MEDIUM_F_SHARP, MEDIUM_G_SHARP, MEDIUM_E, MEDIUM_F_SHARP, 
  MEDIUM_D, MEDIUM_E, MEDIUM_C_SHARP, MEDIUM_D, MEDIUM_B, MEDIUM_C_SHARP, MEDIUM_A, MEDIUM_B, MEDIUM_G_SHARP,
  // Segunda frase: A, G#, A, F#, G#, E, F#, D, E, C, D, A#, C, G, A#, F
  MEDIUM_A, MEDIUM_G_SHARP, MEDIUM_A, MEDIUM_F_SHARP, MEDIUM_G_SHARP, MEDIUM_E, MEDIUM_F_SHARP, 
  MEDIUM_D, MEDIUM_E, MEDIUM_C, MEDIUM_D, MEDIUM_A_SHARP, MEDIUM_C, LOW_G, MEDIUM_A_SHARP, LOW_F
};

static const ToneDuration flightOfTheBumblebeeDurations[] = {
  // Primera frase
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, SHORT_DURATION,
  // Segunda frase
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, SHORT_DURATION
};

static const size_t FLIGHT_OF_THE_BUMBLEBEE_MELODY_LENGTH = sizeof(flightOfTheBumblebeeMelody) / sizeof(flightOfTheBumblebeeMelody[0]);

// Melodía 3: Sonidos inspirados en R2-D2 (Star Wars)
static const ToneFrequency r2d2Melody[] = {
  // Frase 1: Gorjeo rápido ascendente
  HIGH_C, HIGH_E, HIGH_G, PAUSE, HIGH_D, HIGH_F, 
  // Frase 2: Descenso con pausa
  HIGH_E, HIGH_D, HIGH_C, PAUSE, MEDIUM_A, 
  // Frase 3: Pitidos cortos y variados
  HIGH_F, HIGH_A, PAUSE, HIGH_C, HIGH_G, HIGH_D, PAUSE,
  // Frase 4: Tono expresivo con bajada
  MEDIUM_G, HIGH_C, HIGH_E, HIGH_D, PAUSE, HIGH_A, 
  // Frase 5: Gorjeo caótico
  HIGH_F, HIGH_G, HIGH_C, PAUSE, HIGH_E, HIGH_D, HIGH_F, PAUSE, 
  // Frase 6: Final con tono largo
  HIGH_A, MEDIUM_B, HIGH_C, PAUSE, HIGH_G
};

static const ToneDuration r2d2Durations[] = {
  // Frase 1
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  VERY_SHORT_DURATION, VERY_SHORT_DURATION,
  // Frase 2
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  SHORT_DURATION,
  // Frase 3
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION,
  // Frase 4
  SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  VERY_SHORT_DURATION, VERY_SHORT_DURATION,
  // Frase 5
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION,
  // Frase 6
  VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, VERY_SHORT_DURATION, 
  SHORT_DURATION
};

static const size_t R2D2_MELODY_LENGTH = sizeof(r2d2Melody) / sizeof(r2d2Melody[0]);

#endif // MELODIES_H